### ISSUE TITLE
npm Start works but " Build Don't "

### ISSUE THREAD

**Issue by izhar360** [izhar360/cryptoverse#1]
hey, site works with Npm start, but with build it shows 'failed to compile" can you help mate?

**Comment by Rishabhraghwendra18** [comment]
What error you are getting ? may you send me the screenshot of the error

**Comment by izhar360** [comment]
> What error you are getting ? may you send me the screenshot of the error

"Failed to compile"

You can download the source code, i am not able to share a screenshot right now.

**Comment by izhar360** [comment]
did you get it? 😊

**Comment by Rishabhraghwendra18** [comment]
Ya I got it . Looks like issue is with linting . Linting matters most in production build

**Comment by izhar360** [comment]
> Ya I got it . Looks like issue is with linting . Linting matters most in production build

Maybe, it couldn't build it in netlify either i don't know...

**Comment by narayand16** [comment]
@izhar360 Can you assign this to me? I will check what causing it to fail while building. In my first impression, seems like its a configuration issue

**Comment by izhar360** [comment]
> @izhar360 Can you assign this to me? I will check what causing it to fail while building. In my first impression, seems like its a configuration issue

Go on please

**Comment by narayand16** [comment]
> > @izhar360 Can you assign this to me? I will check what causing it to fail while building. In my first impression, seems like its a configuration issue
> 
> Go on please

Hi @izhar360 I am able to build the app. please see screenshot below. Can you try to run lint command on entire project and solve linting issues ? Let me know if the issue occurs at your end with reproduction steps.

![image](https://user-images.githubusercontent.com/29942751/137952352-d22622bc-40df-414b-8007-73b0b6bfee7c.png)

**Comment by izhar360** [comment]
Sure...I'll try and let you know...

**Comment by narayand16** [comment]
@izhar360 What were your findings? I can see this issue is labelled as accepted. Can you close it on my name ?

**Comment by izhar360** [comment]
@narayand16  Thank you mate, and sorry for late checkup #1
